### ISSUE TITLE
pod搜不到，兄弟，你确定上传了？

### ISSUE THREAD

**Issue by hatjs880328s** [HDB-Li/LLDebugToolSwift#1]
pod搜不到，兄弟，你确定上传了？

**Comment by HDB-Li** [comment]
@hatjs880328s  Sure!    

You can run `pod repo update` to update your local pod search list, or run `rm ~/Library/Caches/CocoaPods/search_index.json` to remove your local pod search list,  then run `pod search LLDebugToolSwift`, you will find it at this time.

By the way my pod version is 1.5.3, I don't think the version will affect all searches.

![1537319747465](https://user-images.githubusercontent.com/28746247/45725269-aafa3380-bbec-11e8-9663-87982f6d1c83.jpg)
