### ISSUE TITLE
Not support "generate_multiple_pod_projects: true" in cocoapods

### ISSUE THREAD

**Issue by LouisHors** [HDB-Li/LLDebugToolSwift#7]
A wired problems in LLStorageManager.m that shows "FMDatabaseQueue.h not found" as I updated to 1.3.6 if cocoapods add an option called: generate_multiple_pod_projects
This option enable cocoapods generate each pod as a seperate project, instead of a folder which could speed up indexing for the whole workspace.
This error did not happen in version 1.2.2, it may very helpful if this bug can be fixed🍺
更新到 1.3.6 以后，如果 cocoapods 打开了“generate_multiple_pod_projects” 这个选项，编译就会报错。
之前用 1.2.2 的时候没有遇到这个问题
关于这个选项，可以参照 [掘金这篇文章](https://juejin.im/post/5cf01822e51d45777a126125)
推荐增加对这个选项的支持，非常感谢

**Comment by HDB-Li** [comment]
@LouisHors Thanks Hinata. I will fix this weekend.

**Comment by HDB-Li** [comment]
@LouisHors  I fix it in v1.3.7, when I release a new version, I will close this issue.

**Comment by LouisHors** [comment]
got it, nice🍺🚀

**Comment by HDB-Li** [comment]
@LouisHors  Fix in version 1.3.7, try it!
